server.port=8080
spring.application.name=bff

spring.security.oauth2.client.registration.bff-client.client-id=bff-client
spring.security.oauth2.client.registration.bff-client.client-secret=secret
spring.security.oauth2.client.registration.bff-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.bff-client.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.bff-client.scope=openid,profile

spring.security.oauth2.client.provider.bff-client.issuer-uri=http://127.0.0.1:9000